xrpledger:
  name: chiado
  chainId: 10200
  domainId: 10200
  protocol: ethereum
  rpcUrls:
    - http: https://1rpc.io/gnosis
sepolia:
  name: sepolia
  chainId: 11155111
  domainId: 11155111
  protocol: ethereum
  rpcUrls:
    - http: "https://sepolia.drpc.org"