xrpledger:
  type: messageIdMultisigIsm
  threshold: 1
  validators:
    - "0x2a1F5eB3e84e58e6F1e565306298B9dE1273f203"
sepolia:
  type: messageIdMultisigIsm
  threshold: 1
  validators:
    - "0x2a1F5eB3e84e58e6F1e565306298B9dE1273f203"

